Feature/p CWE b 4435.body scroll lock on modal
dramancompany/remember-ui pull request #15
Opened 2020-11-10 06:07 UTC by arclien

## 작업 내용 (Content)

- 기존에 body scroll lock 잘못 사용하는 것 해결
- 모달 on 모달 / 모달 on 모달 on 모달 등의 다양한 경우 대응

- 기타사항에 자세한?내용 적겠습니다.

## 링크 (Links)

- [JIRA 티켓 이름1](http://jira.dramancompany.com/browse/PCWEB-4435)
- [JIRA 티켓 이름2](http://jira.dramancompany.com/browse/PCWEB-4783)
- [기획 문서](http://wiki.dramancompany.com/pages/viewpage.action?pageId=237469849)

## 기타 사항 (Etc)

```

- 1. 기존에 disableBodyScroll 타겟을 body로 잘못하고있어음
[bodyscrolllock readme](https://github.com/willmcpo/body-scroll-lock#readme)
  - body가 아니라, scroll하고 싶은 타겟을 해야함
- 2. 그런데 우리 모달이 designedModal의 경우 modal의 body가 아니라, body안에서도 특정 div만 스크롤 해야하는 경우가 있음.(제안모달)
  - 모든 modal의 body를 스크롤하게 한다면, 간단하게 remember-ui의 modal body에 target id를 주고 개발하면 되는데, 이번의 경우는 안됨
- 3. 그래서 어쩔 수 없이 커리어웹 코드에서 특정 부분에 bodyScrollLockTargetId 값을 지정해서 모달로 넘기고, 스크롤 하고 싶은 타겟 div에 id를 지정함
- 4. 그런데 모든 modal 사용하는 코드에에 다 id를 넣기엔 너무 힘들고, 기존에 remember-ui를 사용하는 것(프로필웹, 커리어웹, 커뮤니티웹) 에 side effect가 생길 것 같아서
- 5. remember ui에서 각각의 모달(base, designed, confirm)에 random id를 부여해서 modal main body div에 임의로 달았음
- 6. 기존 코드도 데스크탑 뷰에서는 거의 문제 없었으나, 모바일에서 크리티컬 이슈(스크롤 안됨)가 있어서 해당 작업을 진행했습니다.

**결론**
body lock scroll 적용하고 싶은 모달에서, 모달 본문을 scroll 하게 하려면 targetId 을 넘겨야 함.
그 외에 modal body에 scroll이 필요하지 않은 경우( 컨펌 모달 등등 )은 따로 대응 하지 않아도 random 값으로 id를 만들어서 적용함.

알파, 브라보 커리어웹에 적용했습니다.
```

## Merge 전 필요 작업 (Checklist before merge)

## 희망 리뷰 완료 일 (Expected due date)

2020.11.12. Thur

2020-11-10 06:14 UTC, arclien commented on src/components/Modal/BaseModal/index.js
> +        }
사실 clearAllBodyScrollLocks 는 필요 없다고 생각했는데,

모달 띄운 후에 컨펌 모달 떳을경우(제안모달) 
제안작성 종료하시겠습니까??? 에서 "확인" 눌렀을 경우에
클릭 하나에 2개의 모달이 모두 닫혀서( 커리어웹 기존 코드로 콜백 함수를 넘김 )
enableBodyScroll을 제대로 하지 못해서 이슈가 있었음.

그래서 모달이 닫혔을 경우, 모든 open 된 모달이 있는제 체크하고,
모든 모달이 없을 경우에 body에 overflow:hidden 지우도록 했음

2020-11-10 09:46 UTC, arclien commented on src/components/Modal/BaseModal/index.js
> +      }}
Esc 키를 눌렀을 때  모달 꺼지는 로직.
모달은 default로 esc로 모달을 끌 수 있는데, 우리는 컨펌모달, 프로그레스모달은 허용하지 않는다.

[react-modal api](http://reactcommunity.org/react-modal/)

2020-11-12 00:04 UTC, jiseopHan commented on src/components/Modal/BaseModal/index.js
> +        }
style속성을 가져오는 이유는 뭔가요?

2020-11-12 00:12 UTC, jiseopHan commented on src/components/Modal/BaseModal/index.js
> +          if (document.querySelector('body').getAttribute('style')) {
스타일속성의 유무로 clear 여부를 결정하는 건가요?

2020-11-12 00:18 UTC, arclien commented on src/components/Modal/BaseModal/index.js
> +          if (document.querySelector('body').getAttribute('style')) {
`disableBodyScroll` 코드를 살펴보면 결과적으로 body에 style="overflow:hidden"을 해주게 됩니다.

정상적인 경우에는 enable/disable body scroll lock이 하나의 페어로 모달이 열리고 닫힐때 계속적으로 매칭이 되어야 하나

커리어웹에서는 modal on modal의 경우( 제안모달에서 닫기 => 정말 종료하시겠습니까 / 보내기 => 1건 차감되는데 정말 보내시겠습니까) 에서 제안모달을 닫는 코드가 confirm modal에서 컨트롤이 되고있고
이럴 경우 enableBodyScroll을 제대로 해주지 못하게 됩니다(커리어웹 코드에서 매번 콜백으로 넘기지 않느한..)

그래서 모달이 닫힐 때마다, 열려있는 모달이 있는지 체크하고
모달이 열려있지 않지만, body에 아직 overflow:hidden 값이 남아있는 경우에는 clearAllBodyScrollLocks
을 하게 되었습니다.

2020-11-12 00:21 UTC, jiseopHan commented on src/components/Modal/BaseModal/index.js
> +          if (document.querySelector('body').getAttribute('style')) {
음 그렇다면 document.querySelector('body').style.overflow==='hidden' 처럼 세부적으로 체크를 하면 어떨까요?

2020-11-12 00:24 UTC, arclien commented on src/components/Modal/BaseModal/index.js
> +          if (document.querySelector('body').getAttribute('style')) {
혹시라도 정말 혹시라도 body-scroll-lock 모듈 코드가 바뀌면 대응이 안될까봐 그냥 general하게 하긴했는데,
그럴리는 없겠죠??ㅎㅎ
그리고 지금 보니  querySelector 쓰지 않고 바로 body로 접근해도 되겠네요
`document.querySelector('body').style.overflow  ===> document.body.style.overflow`

2020-11-12 00:41 UTC, arclien commented on src/components/Modal/ConfirmModal/index.js
> +    if (!delegateCloseControl && bodyScrollLockTarget) {
`delegateCloseControl` props가 들어가게 된 이유..........
[jira QA issue](http://jira.dramancompany.com/browse/PCWEB-4906)

modal on modal의 경우
제안모달에서 컨펌 모달 떴을 경우,

제안 모달 닫기 클릭 하면 우선 제안 모달에서 `enableBodyScrollLock` 코드가 실행이 되어버리므로
제안모달의 body scroll lock이 풀려 버림.

그런데, 컨펌모달에서 취소를 누르면 다시 제안모달로 포커싱이 되는데, 그럴 경우에는 모달뒤의 body가 스크롤이 되어버림.

이러한 경우( 닫기 버튼을 눌러서 다음 모달에서 정말 닫을지 한번 컨펌하게 되는 경우에는 ) 
`delegateCloseControl` props로  `enableBodyScroll` 함수를  호출할지 말지 여부를 정해야 함.

===========
자꾸 이런 예외 케이스로 props를 넘기고 로직 처리를 하기 싫은데
딱히 방법이 떠오르지 않아서 이러한 코드가 나왔습니다.

의견 주시면 감사하겠습니다.

2020-11-12 06:16 UTC, immigration9 requested changes
지석님 정말 고생 많으셨습니다 😭 

전반적인 로직에 고민의 흔적이 많이 보이네요...
리뷰는 주로 퍼포먼스나 코드 공통화 위주로 진행했습니다!

확인 부탁드립니다 :)

2020-11-12 06:16 UTC, immigration9 commented on src/components/Modal/DesignedModal/index.js
> +  }, [delegateCloseControl, bodyScrollLockTarget]);
여기는 useCallback이 굳이 필요 없을 것 같아요.
https://dmitripavlutin.com/dont-overuse-react-usecallback/

enableBodyScrollLock은 React 구조와 크게 관계가 없어보이는데 util폴더로 빼는건 어떨까요?

2020-11-12 06:16 UTC, immigration9 commented on src/components/Modal/ConfirmModal/index.js
> +    const id = Math.floor(Math.random() * 1000);
random id값은 아무래도 중복의 가능성이 있어서 uuid를 사용하는게 더좋을 것 같아요
https://www.npmjs.com/package/uuid

2020-11-12 06:16 UTC, immigration9 commented on src/components/Modal/DesignedModal/index.js
> +  }, [bodyScrollLockTargetId]);
scroll lock은 별도의 hook으로 구성해보는건 어떨까요? 아무래도 모달 종류가 다양하다보니 공통화가 가능할 것 같아요 :) 

```javascript
export const useScrollLock = () => {
  const [modalId, setModalId] = useState(null);
  const [bodyScrollLockTarget, setBodyScrollLockTarget] = useState(null);
  
  useEffect(() => {
    setModalId(Math.floor(Math.random() * 1000));
    const target = bodyScrollLockTargetId
      ? `#${bodyScrollLockTargetId}`
      : `#designedModal${id}`;
    setBodyScrollLockTarget(target);
  }, [bodyScrollLockTargetId]);

  return {
    modalId,
    bodyScrollLockTarget
  }
}
```

2020-11-12 06:16 UTC, immigration9 commented on src/components/Modal/ConfirmModal/index.js
> +  );
아래와 같은 이유로 _onOk와 _onClose는 callback으로 묶지 않아도 괜찮을 것 같아요!

2020-11-16 10:10 UTC, merged