PCWEB-7818 버튼 컴포넌트들 타이핑 & 리팩터링
dramancompany/remember-ui pull request #76
Opened 2022-06-13 08:18 UTC by kimjeongwonn

> 변경사항이 너무 많아서 diff가 안되고 새로운 파일로 인식하는 게 많네요 ㅠㅠ...

## 작업 내용 (Content) 📝

- 아래 컴포넌트들을 타이핑 했습니다.
  - BaseButton
    - 스타일컴포넌트 내에서 사용되지 않는 large prop에 대한 정의 제거
  - CustomButton
  - LinkButton
  - MoreButton
    - 스타일컴포넌트 내에 정체불명의 src 속성 제거
    - attrs을 통해 전달하는 속성 제거
  - NewBaseButton
  - TopButton
    - scroll이후에 callback 추가

- 전체적으로 onClick 이벤트 방지 로직을 수정
  - 기존에는 _onClick 핸들러를 만들고 핸들러 내부에서 처리
  - 아예 전달되지 않도록 변경

## 스크린샷 (Screenshot) 📷

## 링크 (Links) 🔗

- [PCWEB-7818](https://dramancompany.atlassian.net/browse/PCWEB-7818)

## 기타 사항 (Etc) 🔖

## 테스트 Checklist (Test Checklist) ✅

- 꼭 테스트 해봐야하는 시나리오를 적어주세요
- [ ] eg) Test case

## 희망 리뷰 완료 일 (Expected due date) ⏰

`202X.X.X. Wed`

2022-06-14 06:09 UTC, qkraudghgh requested changes
deprecated된 color는 new color로 바꿔주시면 좋을 것 같아요
(deprecated된 component라고 하더라도)
만약 대응되는 color가 없다면 차라리 hex code로 하는게 어떨까 싶습니다~

2022-06-14 06:09 UTC, qkraudghgh commented on src/components/Button/NewBaseButton/NewBaseButton.styles.ts
> +  border-radius: 4px;
css 순서가 바뀌어야될 것 같아요~

```suggestion
  box-sizing: border-box;
  cursor: ${({ isLoading, disabled }) =>
    isLoading || disabled ? 'default' : 'pointer'};
  font-weight: 400;
  border-radius: 4px;
  
  ${({ size = 'small' }) => css`
    height: ${NEW_BASE_BUTTON_SIZES[size].height};
    font-size: ${NEW_BASE_BUTTON_SIZES[size].fontSize};
    min-width: ${NEW_BASE_BUTTON_SIZES[size].minWidth};
    padding: ${NEW_BASE_BUTTON_SIZES[size].padding};
    border-radius: ${size === 'small' ? '2px' : '4px'};
  `};
```

2022-06-14 06:09 UTC, qkraudghgh commented on src/components/Button/NewBaseButton/NewBaseButton.styles.ts
> +  color: ${contents999};
여기두요 ~!

2022-06-27 07:54 UTC, kimjeongwonn commented on src/components/Button/NewBaseButton/NewBaseButton.styles.ts
> +  border-radius: 4px;
감사합니다! 수정하겠습니다!

2022-06-27 07:58 UTC, kimjeongwonn commented
@qkraudghgh deprecated된 색상은 1:1매칭되는 것들만 수정하면 될까요? (예: primary100 -> contents000)
예를들어 blue100과 accent200은 비슷하긴 한데 완전 다른 색이니 대체하는 게 아니라 hex로 빼면 될까요?

2022-06-27 08:01 UTC, qkraudghgh commented
@kimjeongwonn 
마이그레이션 가이드에도 써있긴하지만
구체적인 용례를 모르면 애매한 것들은 private-디자인_개발이었나 그 채널에서 한번 여쭤봐주세요! ㅎㅎ

2022-06-27 12:34 UTC, kimjeongwonn commented
@qkraudghgh 대응색들 우석님께 확인받아서 수정했습니다! 단 color props 이름에 의존성이 있는 색들은 hex컬러로 전달하였습니다...
<Button color="yellow" /> 처럼 사용하는 경우에는 yellow라는 명시가 있기 때문에 ㅠㅠ... 추후 논의 이후에 props의 기본값을 blue로 바꾸는 등 조치를 취하면 좋을 것 같습니다~!

2022-07-01 00:52 UTC, merged